CREATE TABLE `in_kind_categories` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`slug` text NOT NULL,
	`name` text NOT NULL,
	`name_am` text,
	`description` text,
	`icon` text,
	`pillar_id` integer,
	`default_unit` text DEFAULT 'items' NOT NULL,
	`requires_expiry` integer DEFAULT false NOT NULL,
	`requires_sizing` integer DEFAULT false NOT NULL,
	`requires_transport` integer DEFAULT false NOT NULL,
	`acceptance_note` text,
	`is_accepting_now` integer DEFAULT true NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`is_active` integer DEFAULT true NOT NULL,
	`created_by` text,
	`updated_by` text,
	`created_at` integer DEFAULT (unixepoch('subsec') * 1000) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch('subsec') * 1000) NOT NULL,
	`deleted_at` integer,
	`deleted_by` text,
	FOREIGN KEY (`pillar_id`) REFERENCES `pillars`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`created_by`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`updated_by`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`deleted_by`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE UNIQUE INDEX `in_kind_categories_slug_unique` ON `in_kind_categories` (`slug`);--> statement-breakpoint
CREATE INDEX `in_kind_categories_active_idx` ON `in_kind_categories` (`is_active`,`sort_order`);--> statement-breakpoint
CREATE INDEX `in_kind_categories_pillar_idx` ON `in_kind_categories` (`pillar_id`);--> statement-breakpoint
CREATE TABLE `in_kind_donation_items` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`in_kind_donation_id` integer NOT NULL,
	`category_id` integer,
	`description` text NOT NULL,
	`quantity` integer DEFAULT 1 NOT NULL,
	`unit` text DEFAULT 'items' NOT NULL,
	`condition` text DEFAULT 'good' NOT NULL,
	`age_group` text DEFAULT 'any' NOT NULL,
	`gender` text DEFAULT 'unisex' NOT NULL,
	`size_range` text,
	`brand_or_model` text,
	`is_perishable` integer DEFAULT false NOT NULL,
	`expires_on` text,
	`needs_refrigeration` integer DEFAULT false NOT NULL,
	`estimated_value` integer,
	`currency` text DEFAULT 'ETB' NOT NULL,
	`notes` text,
	`accepted_quantity` integer,
	`intake_note` text,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`created_at` integer DEFAULT (unixepoch('subsec') * 1000) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch('subsec') * 1000) NOT NULL,
	`deleted_at` integer,
	FOREIGN KEY (`in_kind_donation_id`) REFERENCES `in_kind_donations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`category_id`) REFERENCES `in_kind_categories`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE INDEX `in_kind_items_donation_idx` ON `in_kind_donation_items` (`in_kind_donation_id`,`sort_order`);--> statement-breakpoint
CREATE INDEX `in_kind_items_category_idx` ON `in_kind_donation_items` (`category_id`);--> statement-breakpoint
CREATE INDEX `in_kind_items_expiry_idx` ON `in_kind_donation_items` (`expires_on`);--> statement-breakpoint
CREATE TABLE `in_kind_donation_photos` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`in_kind_donation_id` integer NOT NULL,
	`file_id` integer NOT NULL,
	`item_id` integer,
	`caption` text,
	`source` text DEFAULT 'donor' NOT NULL,
	`created_at` integer DEFAULT (unixepoch('subsec') * 1000) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch('subsec') * 1000) NOT NULL,
	`deleted_at` integer,
	FOREIGN KEY (`in_kind_donation_id`) REFERENCES `in_kind_donations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`file_id`) REFERENCES `files`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`item_id`) REFERENCES `in_kind_donation_items`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE INDEX `in_kind_photos_donation_idx` ON `in_kind_donation_photos` (`in_kind_donation_id`);--> statement-breakpoint
CREATE TABLE `in_kind_donations` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`reference_code` text NOT NULL,
	`donor_id` integer,
	`donor_name` text NOT NULL,
	`donor_email` text,
	`donor_phone` text,
	`donor_type` text DEFAULT 'individual' NOT NULL,
	`organisation_name` text,
	`is_diaspora` integer DEFAULT false NOT NULL,
	`preferred_contact_channel` text DEFAULT 'phone' NOT NULL,
	`best_time_to_contact` text,
	`summary` text NOT NULL,
	`item_count` integer DEFAULT 0 NOT NULL,
	`total_quantity` integer DEFAULT 0 NOT NULL,
	`estimated_value` integer,
	`currency` text DEFAULT 'ETB' NOT NULL,
	`valuation_basis` text DEFAULT 'donor_estimate' NOT NULL,
	`is_perishable` integer DEFAULT false NOT NULL,
	`needs_cold_storage` integer DEFAULT false NOT NULL,
	`has_restricted_items` integer DEFAULT false NOT NULL,
	`restricted_items_note` text,
	`designation_type` text DEFAULT 'general_fund' NOT NULL,
	`designation_pillar_id` integer,
	`designation_initiative_id` integer,
	`region_id` integer,
	`handover_method` text DEFAULT 'dropoff' NOT NULL,
	`pickup_contact_name` text,
	`pickup_contact_phone` text,
	`pickup_address_line` text,
	`pickup_city` text,
	`pickup_landmark` text,
	`access_notes` text,
	`load_size` text DEFAULT 'car_boot' NOT NULL,
	`estimated_weight_kg` integer,
	`requires_vehicle` integer DEFAULT false NOT NULL,
	`requires_help_loading` integer DEFAULT false NOT NULL,
	`available_from` text,
	`available_until` text,
	`receipt_requested` integer DEFAULT false NOT NULL,
	`tax_receipt_required` integer DEFAULT false NOT NULL,
	`tax_id_number` text,
	`is_anonymous` integer DEFAULT false NOT NULL,
	`recognition_name` text,
	`donor_message` text,
	`heard_about` text,
	`consent_to_contact_at` integer,
	`status` text DEFAULT 'offered' NOT NULL,
	`reviewed_by_id` text,
	`reviewed_at` integer,
	`review_notes` text,
	`decline_reason` text,
	`assigned_to_id` text,
	`scheduled_for` text,
	`scheduled_window` text,
	`received_at` integer,
	`received_by_id` text,
	`intake_notes` text,
	`distribution_notes` text,
	`acknowledgement_sent_at` integer,
	`language` text DEFAULT 'en' NOT NULL,
	`is_read` integer DEFAULT false NOT NULL,
	`created_at` integer DEFAULT (unixepoch('subsec') * 1000) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch('subsec') * 1000) NOT NULL,
	`deleted_at` integer,
	FOREIGN KEY (`donor_id`) REFERENCES `donors`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`designation_pillar_id`) REFERENCES `pillars`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`designation_initiative_id`) REFERENCES `future_initiatives`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`region_id`) REFERENCES `regions`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`reviewed_by_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`assigned_to_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`received_by_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE UNIQUE INDEX `in_kind_donations_reference_code_unique` ON `in_kind_donations` (`reference_code`);--> statement-breakpoint
CREATE INDEX `in_kind_donations_status_idx` ON `in_kind_donations` (`status`,`created_at`);--> statement-breakpoint
CREATE INDEX `in_kind_donations_donor_idx` ON `in_kind_donations` (`donor_id`,`created_at`);--> statement-breakpoint
CREATE INDEX `in_kind_donations_designation_idx` ON `in_kind_donations` (`designation_type`,`designation_pillar_id`);--> statement-breakpoint
CREATE INDEX `in_kind_donations_scheduled_idx` ON `in_kind_donations` (`scheduled_for`,`status`);--> statement-breakpoint
CREATE INDEX `in_kind_donations_region_idx` ON `in_kind_donations` (`region_id`);